"""Admin action service — file-based store of admin actions per user."""

from typing import TYPE_CHECKING, List, Optional
from uuid import uuid4

from authglow.core.config import get_settings
from authglow.core.datetime import utcnow
from authglow.core.pii import hash_pii, mask_ip

if TYPE_CHECKING:
    from authglow.repositories.protocols import AdminActionRepository


class AdminAction:
    """A single admin action record.

    This dataclass is the service-side representation of an
    admin action. It is used by ``record_action`` to return a
    structured object to the caller (in case a future caller
    needs the generated ``id`` / ``timestamp`` synchronously).

    Note: the ``id`` and ``timestamp`` generated here are
    **distinct** from the ones persisted by the repository
    (which generates its own ``id`` and ``timestamp`` for
    cross-process safety). No current route consumes the return
    value of ``record_action``, so this inconsistency is latent.
    """

    def __init__(
        self,
        admin_user_id: str,
        admin_email: str,
        action_type: str,
        target_user_id: str,
        target_user_email: Optional[str] = None,
        details: Optional[dict] = None,
        ip_address: Optional[str] = None,
    ):
        self.id = str(uuid4())
        self.admin_user_id = admin_user_id
        self.admin_email = admin_email
        self.action_type = action_type
        self.target_user_id = target_user_id
        self.target_user_email = target_user_email
        self.details = details or {}
        self.ip_address = ip_address
        self.timestamp = utcnow()

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "admin_user_id": self.admin_user_id,
            "admin_email": self.admin_email,
            "action_type": self.action_type,
            "target_user_id": self.target_user_id,
            "target_user_email": self.target_user_email,
            "details": self.details,
            "ip_address": self.ip_address,
            "timestamp": self.timestamp.isoformat(),
        }

    def to_masked_dict(self, secret_key: str) -> dict:
        """Return the *masked* view for persistence (VAPT-081).

        ``admin_email``, ``target_user_email``, and any
        ``details`` keys containing ``"email"`` are HMAC-hashed.
        ``ip_address`` is truncated to ``/24`` / ``/48``.
        """
        d = self.to_dict()
        d["admin_email"] = hash_pii(self.admin_email, secret_key)
        d["target_user_email"] = hash_pii(self.target_user_email, secret_key)
        d["ip_address"] = mask_ip(self.ip_address)
        if isinstance(self.details, dict):
            masked_details: dict = {}
            for k, v in self.details.items():
                if "email" in k.lower() and isinstance(v, str):
                    masked_details[k] = hash_pii(v, secret_key)
                else:
                    masked_details[k] = v
            d["details"] = masked_details
        return d

    @classmethod
    def from_dict(cls, data: dict) -> "AdminAction":
        action = cls(
            admin_user_id=data["admin_user_id"],
            admin_email=data["admin_email"],
            action_type=data["action_type"],
            target_user_id=data["target_user_id"],
            target_user_email=data.get("target_user_email"),
            details=data.get("details", {}),
            ip_address=data.get("ip_address"),
        )
        action.id = data["id"]
        from datetime import datetime as dt

        action.timestamp = dt.fromisoformat(data["timestamp"])
        return action


class AdminActionService:
    """Service for recording and querying admin actions."""

    RETENTION_DAYS = 365

    def __init__(self, repository: Optional["AdminActionRepository"] = None) -> None:
        """Initialise the service.

        ``repository`` is optional; when ``None`` a fresh
        ``FileAdminActionRepository`` is created via the FastAPI
        factory. The ``__init__`` no longer touches ``fsspec`` or
        ``os`` directly — both backend-bypass bugs from the
        pre-refactor implementation are fixed by delegating all
        I/O to the repository.
        """
        self.settings = get_settings()
        if repository is None:
            from authglow.repositories.dependencies import (
                get_admin_action_repository,
            )

            self._repo: "AdminActionRepository" = get_admin_action_repository()
        else:
            self._repo = repository

    async def record_action(
        self,
        admin_user_id: str,
        admin_email: str,
        action_type: str,
        target_user_id: str,
        target_user_email: Optional[str] = None,
        details: Optional[dict] = None,
        ip_address: Optional[str] = None,
    ) -> AdminAction:
        """Persist a new admin action.

        Returns an ``AdminAction`` instance whose ``id`` and
        ``timestamp`` are generated by the service (not the
        repository). The persisted record has its own
        ``id`` / ``timestamp`` for cross-process safety; see
        :class:`AdminAction` for the inconsistency note.
        """
        action = AdminAction(
            admin_user_id=admin_user_id,
            admin_email=admin_email,
            action_type=action_type,
            target_user_id=target_user_id,
            target_user_email=target_user_email,
            details=details,
            ip_address=ip_address,
        )
        # VAPT-081: mask PII before persistence.
        masked = action.to_masked_dict(self.settings.secret_key)
        await self._repo.record(
            admin_user_id=masked["admin_user_id"],
            admin_email=masked["admin_email"],
            action_type=masked["action_type"],
            target_user_id=masked["target_user_id"],
            target_user_email=masked["target_user_email"],
            details=masked["details"],
            ip_address=masked["ip_address"],
        )
        return action

    async def delete_for_user(self, user_id: str) -> int:
        """Drop **every** admin-action record targeting ``user_id``.

        VAPT-082 / GDPR right-to-erasure. The repository key
        for admin actions is ``target_user_id`` (the user that
        the action was performed against); the GDPR purge path
        passes the user that was deleted.
        """
        return await self._repo.delete_for_user(target_user_id=user_id)

    async def get_admin_actions(
        self,
        target_user_id: str,
        limit: int = 50,
        offset: int = 0,
    ) -> tuple[List[dict], int]:
        """Return a paginated slice of actions against a user, plus
        the total count. Newest first.

        The repository performs glob + read; the service is a
        thin pass-through. Per-file corrupt-JSON handling is the
        repository's responsibility (``_read_json`` returns
        ``None`` for missing / corrupt files).
        """
        return await self._repo.list_for_user(target_user_id, limit=limit, offset=offset)
