"""Security events service — file-based store of security events per user."""

from typing import TYPE_CHECKING, List, Optional
from uuid import uuid4

from authglow.core.config import get_settings
from authglow.core.datetime import utcnow

if TYPE_CHECKING:
    from authglow.repositories.protocols import SecurityEventRepository


class SecurityEvent:
    """A single security event record.

    This dataclass is the service-side representation of a
    security event. It is used by ``record_event`` to return a
    structured object to the caller (in case a future caller
    needs the generated ``id`` / ``timestamp`` synchronously).

    Note: the ``id`` and ``timestamp`` generated here are
    **distinct** from the ones persisted by the repository
    (which generates its own ``id`` and ``timestamp`` for
    cross-process safety). No current route consumes the return
    value of ``record_event``, so this inconsistency is latent.
    """

    def __init__(
        self,
        user_id: str,
        event_type: str,
        email: Optional[str] = None,
        description: Optional[str] = None,
        ip_address: Optional[str] = None,
        metadata: Optional[dict] = None,
    ):
        self.id = str(uuid4())
        self.user_id = user_id
        self.event_type = event_type
        self.email = email
        self.description = description
        self.ip_address = ip_address
        self.metadata = metadata or {}
        self.timestamp = utcnow()

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "user_id": self.user_id,
            "event_type": self.event_type,
            "email": self.email,
            "description": self.description,
            "ip_address": self.ip_address,
            "metadata": self.metadata,
            "timestamp": self.timestamp.isoformat(),
        }

    @classmethod
    def from_dict(cls, data: dict) -> "SecurityEvent":
        event = cls(
            user_id=data["user_id"],
            event_type=data["event_type"],
            email=data.get("email"),
            description=data.get("description"),
            ip_address=data.get("ip_address"),
            metadata=data.get("metadata", {}),
        )
        event.id = data["id"]
        from datetime import datetime as dt

        event.timestamp = dt.fromisoformat(data["timestamp"])
        return event


class SecurityEventService:
    """Service for recording and querying security events."""

    RETENTION_DAYS = 365

    def __init__(self, repository: Optional["SecurityEventRepository"] = None) -> None:
        """Initialise the service.

        ``repository`` is optional; when ``None`` a fresh
        ``FileSecurityEventRepository`` is created via the FastAPI
        factory. The ``__init__`` no longer touches ``fsspec`` or
        ``os`` directly — both backend-bypass bugs from the
        pre-refactor implementation are fixed by delegating all
        I/O to the repository.
        """
        self.settings = get_settings()
        if repository is None:
            from authglow.repositories.dependencies import (
                get_security_event_repository,
            )

            self._repo: "SecurityEventRepository" = get_security_event_repository()
        else:
            self._repo = repository

    async def record_event(
        self,
        user_id: str,
        event_type: str,
        email: Optional[str] = None,
        description: Optional[str] = None,
        ip_address: Optional[str] = None,
        metadata: Optional[dict] = None,
    ) -> SecurityEvent:
        """Persist a new security event.

        Returns a ``SecurityEvent`` instance whose ``id`` and
        ``timestamp`` are generated by the service (not the
        repository). The persisted record has its own
        ``id`` / ``timestamp`` for cross-process safety; see
        :class:`SecurityEvent` for the inconsistency note.
        """
        event = SecurityEvent(
            user_id=user_id,
            event_type=event_type,
            email=email,
            description=description,
            ip_address=ip_address,
            metadata=metadata,
        )
        await self._repo.record(
            user_id=user_id,
            event_type=event_type,
            email=email,
            description=description,
            ip_address=ip_address,
            metadata=metadata,
        )
        return event

    async def get_security_events(
        self,
        user_id: str,
        limit: int = 50,
        offset: int = 0,
    ) -> tuple[List[dict], int]:
        """Return a paginated slice of security events for a user
        (newest first) plus the total count.

        The repository performs glob + read; the service is a
        thin pass-through. Per-file corrupt-JSON handling is the
        repository's responsibility (``_read_json`` returns
        ``None`` for missing / corrupt files).
        """
        return await self._repo.list_for_user(user_id, limit=limit, offset=offset)
