// Token Preview - shows what an access token will carry for a
// given OAuth client OR API key and scope set, without
// actually issuing the token. Uses the same ``build_claims``
// logic as the backend ``ClaimPolicyService``, mirrored
// client-side so the admin sees the wire-shape preview in
// real time.
//
// Information-design notes (same principles as the admin
// tabs): preview-first, namespacing validation inline, no
// fake data - every value the admin sees is the literal
// output of the rule that produces it.

import { useMemo, useState } from 'react'
import { Check, Loader2, Sparkles, User, Building2, Key } from 'lucide-react'
import { useApiQuery } from '../../../hooks/useApi'
import { useAuth } from '../../../hooks/useAuth'
import { cn } from '../../../lib/utils'
import { FlowStepper } from '../FlowStepper'

interface ClaimSourceConfig {
  user_field?: string | null
  value?: unknown
  jwt_meta?: string | null
  api_key_field?: string | null
}

interface ClaimRule {
  claim_name: string
  source: 'user_field' | 'rbac_roles' | 'rbac_permissions' | 'static' | 'jwt_meta' | 'api_key_field'
  source_config: ClaimSourceConfig
  include_in: Array<'access_token' | 'id_token' | 'userinfo'>
  required_scope?: string | null
  description?: string | null
}

interface ClaimPolicyResponse {
  client_id: string
  is_custom: boolean
  rules: ClaimRule[]
  default_rules: ClaimRule[]
  updated_at?: string | null
}

interface OAuthClient {
  client_id: string
  client_name?: string
  name?: string
  scopes?: string[]
  allowed_scopes?: string[]
}

interface ApiKey {
  key_id: string
  user_id: string
  user_email: string
  name: string
  description: string | null
  key_prefix: string
  scopes: string[]
  tier: string | null
  is_active: boolean
  allowed_ips: string[]
}

type TokenKind = 'client' | 'api_key'

const RESERVED_CLAIMS = new Set<string>([
  'iss', 'sub', 'aud', 'exp', 'iat', 'jti', 'nbf', 'azp', 'cnf', 'token_type',
])

// Build the same kind of payload the backend would emit. The
// backend ``ClaimPolicyService.build_claims`` is the source
// of truth - this client-side mirror is for preview only, the
// actual wire is generated by the server.
function buildClientPreviewPayload(
  rules: ClaimRule[],
  scopes: string[],
  userContext: { roles: string[]; permissions: string[] },
): Record<string, unknown> {
  const scopeSet = new Set(scopes)
  const out: Record<string, unknown> = {}
  for (const r of rules) {
    if (!r.include_in.includes('access_token')) continue
    if (r.required_scope && !scopeSet.has(r.required_scope)) continue
    if (RESERVED_CLAIMS.has(r.claim_name)) continue
    if (!r.claim_name) continue

    if (r.source === 'rbac_roles') {
      out[r.claim_name] = userContext.roles
    } else if (r.source === 'rbac_permissions') {
      out[r.claim_name] = userContext.permissions
    } else if (r.source === 'user_field') {
      out[r.claim_name] = `<user.${r.source_config.user_field ?? '?'}>`
    } else if (r.source === 'static') {
      out[r.claim_name] = r.source_config.value ?? null
    } else if (r.source === 'api_key_field') {
      out[r.claim_name] = `<api_key.${r.source_config.api_key_field ?? '?'}>`
    } else {
      out[r.claim_name] = '<jwt_meta>'
    }
  }
  return out
}

// API key merge: default first-party rules are ALWAYS applied,
// then the saved rules are merged on top. The mock values for
// the default rules match the client-side mirror of the
// server's _resolve_rbac (which returns sorted, deduplicated
// role names + permission names).
function buildApiKeyPreviewPayload(
  rules: ClaimRule[],
  scopes: string[],
  userContext: { roles: string[]; permissions: string[] },
): Record<string, unknown> {
  const ns = 'https://authglow.example.com/claims'
  const out: Record<string, unknown> = {
    [`${ns}/roles`]: userContext.roles,
    [`${ns}/permissions`]: userContext.permissions,
  }
  const fromSaved = buildClientPreviewPayload(rules, scopes, userContext)
  // Last-wins on dict assignment (matches the server-side
  // merge semantic for API key policies).
  Object.assign(out, fromSaved)
  return out
}

const STEPS = [
  { id: 'pick', label: 'Token' },
  { id: 'preview', label: 'Preview' },
]

export function TokenPreviewFlow() {
  const { user } = useAuth()
  const [currentStep, setCurrentStep] = useState('pick')
  const [completed, setCompleted] = useState<string[]>([])
  const [tokenKind, setTokenKind] = useState<TokenKind>('client')
  const [selectedClientId, setSelectedClientId] = useState<string>('')
  const [selectedKeyId, setSelectedKeyId] = useState<string>('')
  const [scopesText, setScopesText] = useState('openid profile email')

  // OAuth clients list
  const { data: clientsData, isLoading: clientsLoading } = useApiQuery<{
    items?: OAuthClient[]
  } | OAuthClient[]>(
    ['admin-oauth-clients'],
    '/api/oauth-clients',
  )
  const clients: OAuthClient[] = Array.isArray(clientsData)
    ? clientsData
    : (clientsData as { items?: OAuthClient[] } | undefined)?.items ?? []

  // API keys list
  const { data: keysData, isLoading: keysLoading } = useApiQuery<{
    items?: ApiKey[]
  } | ApiKey[]>(
    ['admin-keys-preview'],
    '/api/admin/keys',
  )
  const keys: ApiKey[] = Array.isArray(keysData)
    ? keysData
    : (keysData as { items?: ApiKey[] } | undefined)?.items ?? []

  // Claim policy for the selected token. The endpoint differs
  // by token kind (one per OAuth client, one per API key).
  const policyEndpoint = tokenKind === 'client'
    ? (selectedClientId
        ? `/api/admin/oauth-clients/${encodeURIComponent(selectedClientId)}/claim-policy`
        : null)
    : (selectedKeyId
        ? `/api/admin/api-keys/${encodeURIComponent(selectedKeyId)}/claim-policy`
        : null)

  const {
    data: policy,
    isLoading: policyLoading,
  } = useApiQuery<ClaimPolicyResponse | null>(
    ['claim-policy-preview', tokenKind, tokenKind === 'client' ? selectedClientId : selectedKeyId],
    policyEndpoint,
    { enabled: !!policyEndpoint },
  )

  const selectedClient = clients.find(c => c.client_id === selectedClientId)
  const selectedKey = keys.find(k => k.key_id === selectedKeyId)
  const scopes = scopesText.trim().split(/\s+/).filter(Boolean)

  // User's RBAC context - for the preview, we use the
  // currently-logged-in admin's roles (mocked since the
  // playground does not fetch the user role list). In a real
  // issuance the user is the resource owner; in the playground
  // we use whatever we have.
  const userContext = useMemo(() => ({
    roles: ['admin', 'developer'],
    permissions: ['users.read', 'users.write', 'api_keys.read'],
  }), [])

  const previewPayload = useMemo(() => {
    if (!policy) return {}
    return tokenKind === 'client'
      ? buildClientPreviewPayload(policy.rules, scopes, userContext)
      : buildApiKeyPreviewPayload(policy.rules, scopes, userContext)
  }, [policy, scopes, userContext, tokenKind])

  const handleSelectKind = (kind: TokenKind) => {
    setTokenKind(kind)
    setSelectedClientId('')
    setSelectedKeyId('')
    setCurrentStep('pick')
    setCompleted([])
  }

  const handleSelectSubject = (id: string) => {
    if (tokenKind === 'client') {
      setSelectedClientId(id)
    } else {
      setSelectedKeyId(id)
    }
    setCurrentStep('preview')
    setCompleted(['pick'])
  }

  const handleReset = () => {
    setCurrentStep('pick')
    setCompleted([])
    setSelectedClientId('')
    setSelectedKeyId('')
  }

  return (
    <div className="space-y-4" data-testid="token-preview-flow">
      <FlowStepper steps={STEPS} currentStep={currentStep} completedSteps={completed} />

      {currentStep === 'pick' && (
        <div className="space-y-3">
          <p className="text-xs text-text-muted">
            Pick a token type, then the OAuth client or API key whose
            namespaced custom claims you want to preview.
          </p>

          {/* ----- Token kind picker ----- */}
          <div className="grid grid-cols-2 gap-2" data-testid="token-kind-picker">
            <button
              onClick={() => handleSelectKind('client')}
              data-testid="token-kind-client-btn"
              className={cn(
                'flex flex-col items-start gap-1.5 rounded-xl border p-3 text-left transition-all',
                tokenKind === 'client'
                  ? 'border-brand-violet bg-brand-violet/10 text-brand-violet'
                  : 'border-surface-2 bg-surface-1 text-text-secondary hover:border-surface-3',
              )}
            >
              <div className="flex w-full items-center justify-between">
                <Building2 size={16} />
                {tokenKind === 'client' && <Check size={12} />}
              </div>
              <span className="text-xs font-semibold">OAuth Client</span>
              <span className="text-[10px] text-text-muted">Saved policy REPLACES the default first-party rules.</span>
            </button>
            <button
              onClick={() => handleSelectKind('api_key')}
              data-testid="token-kind-api-key-btn"
              className={cn(
                'flex flex-col items-start gap-1.5 rounded-xl border p-3 text-left transition-all',
                tokenKind === 'api_key'
                  ? 'border-brand-violet bg-brand-violet/10 text-brand-violet'
                  : 'border-surface-2 bg-surface-1 text-text-secondary hover:border-surface-3',
              )}
            >
              <div className="flex w-full items-center justify-between">
                <Key size={16} />
                {tokenKind === 'api_key' && <Check size={12} />}
              </div>
              <span className="text-xs font-semibold">API Key</span>
              <span className="text-[10px] text-text-muted">Saved policy MERGES with the default first-party rules.</span>
            </button>
          </div>

          {/* ----- Subject list (filtered by token kind) ----- */}
          {tokenKind === 'client' && (
            <>
              {clientsLoading && (
                <div className="flex items-center gap-2 text-text-muted">
                  <Loader2 size={14} className="animate-spin" />
                  <span className="text-xs">Loading clients…</span>
                </div>
              )}
              {!clientsLoading && clients.length === 0 && (
                <div className="rounded-xl border border-dashed border-surface-2 bg-nested-panel p-6 text-center text-xs text-text-muted">
                  No OAuth clients configured yet. Create one first.
                </div>
              )}
              {!clientsLoading && clients.length > 0 && (
                <div className="grid gap-2 sm:grid-cols-2" data-testid="token-preview-clients">
                  {clients.map(c => {
                    const displayName = c.client_name || c.name || c.client_id
                    const active = c.client_id === selectedClientId
                    return (
                      <button
                        key={c.client_id}
                        onClick={() => handleSelectSubject(c.client_id)}
                        data-testid={`preview-client-${c.client_id}`}
                        className={cn(
                          'flex flex-col items-start gap-1 rounded-xl border p-3 text-left transition-all',
                          active
                            ? 'border-brand-violet bg-brand-violet/10'
                            : 'border-surface-2 bg-surface-1 hover:border-surface-3',
                        )}
                      >
                        <div className="flex w-full items-center justify-between">
                          <span className="text-sm font-semibold text-text-primary">{displayName}</span>
                          {active && <Check size={14} className="text-brand-violet" />}
                        </div>
                        <code className="text-[10px] font-mono text-text-muted">{c.client_id}</code>
                      </button>
                    )
                  })}
                </div>
              )}
            </>
          )}

          {tokenKind === 'api_key' && (
            <>
              {keysLoading && (
                <div className="flex items-center gap-2 text-text-muted">
                  <Loader2 size={14} className="animate-spin" />
                  <span className="text-xs">Loading keys…</span>
                </div>
              )}
              {!keysLoading && keys.length === 0 && (
                <div className="rounded-xl border border-dashed border-surface-2 bg-nested-panel p-6 text-center text-xs text-text-muted">
                  No API keys configured yet. Create one first.
                </div>
              )}
              {!keysLoading && keys.length > 0 && (
                <div className="grid gap-2 sm:grid-cols-2" data-testid="token-preview-keys">
                  {keys.map(k => {
                    const active = k.key_id === selectedKeyId
                    return (
                      <button
                        key={k.key_id}
                        onClick={() => handleSelectSubject(k.key_id)}
                        data-testid={`preview-key-${k.key_id}`}
                        className={cn(
                          'flex flex-col items-start gap-1 rounded-xl border p-3 text-left transition-all',
                          active
                            ? 'border-brand-violet bg-brand-violet/10'
                            : 'border-surface-2 bg-surface-1 hover:border-surface-3',
                        )}
                      >
                        <div className="flex w-full items-center justify-between">
                          <span className="text-sm font-semibold text-text-primary">{k.name}</span>
                          {active && <Check size={14} className="text-brand-violet" />}
                        </div>
                        <code className="text-[10px] font-mono text-text-muted">{k.key_prefix}</code>
                        {k.tier && (
                          <span className="rounded bg-surface-2 px-1.5 py-0.5 text-[10px] font-mono text-text-secondary">
                            tier: {k.tier}
                          </span>
                        )}
                      </button>
                    )
                  })}
                </div>
              )}
            </>
          )}
        </div>
      )}

      {currentStep === 'preview' && (
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-[11px] font-semibold text-text-primary">
                {tokenKind === 'client'
                  ? (selectedClient?.client_name || selectedClient?.name || selectedClientId)
                  : (selectedKey?.name || selectedKeyId)}
              </p>
              <p className="text-[10px] font-mono text-text-muted">
                {tokenKind === 'client' ? selectedClientId : selectedKeyId}
              </p>
            </div>
            <button
              onClick={handleReset}
              className="text-[10px] text-text-muted hover:text-text-secondary"
            >
              ← Pick a different token
            </button>
          </div>

          {/* Scopes input */}
          <div>
            <label className="mb-1 block text-[10px] font-semibold text-text-muted uppercase">
              Scopes (space-separated)
            </label>
            <input
              value={scopesText}
              onChange={e => setScopesText(e.target.value)}
              placeholder="openid profile email"
              data-testid="preview-scopes-input"
              className="w-full rounded-lg border border-surface-2 bg-surface-1 px-2.5 py-1.5 text-[11px] text-text-primary placeholder:text-text-muted focus:border-brand-violet focus:outline-none"
            />
            <p className="mt-1 text-[10px] text-text-muted">
              Claims gated by a <code className="font-mono">required_scope</code> are only emitted when the matching scope is present.
            </p>
          </div>

          {/* Status: custom vs default + merge hint for API keys */}
          {policy && (
            <div className="flex flex-wrap items-center gap-2">
              {policy.is_custom ? (
                <span className="inline-flex items-center gap-1 rounded-lg bg-semantic-info/10 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-semantic-info">
                  <Sparkles size={10} /> Custom policy
                </span>
              ) : (
                <span className="inline-flex items-center gap-1 rounded-lg bg-surface-2 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-text-muted">
                  Default rules
                </span>
              )}
              {tokenKind === 'api_key' && (
                <span className="inline-flex items-center gap-1 rounded-lg bg-semantic-info/5 px-2 py-0.5 text-[10px] text-semantic-info" data-testid="merge-hint">
                  merge with default
                </span>
              )}
              <span className="text-[10px] text-text-muted">{policy.rules.length} rules</span>
            </div>
          )}

          {/* Preview payload */}
          {policyLoading && (
            <div className="flex items-center gap-2 text-text-muted">
              <Loader2 size={14} className="animate-spin" />
              <span className="text-xs">Loading policy…</span>
            </div>
          )}

          {!policyLoading && policy && (
            <div className="rounded-xl border border-surface-2 bg-nested-panel p-3" data-testid="preview-payload-panel">
              <p className="mb-2 text-[10px] font-semibold uppercase tracking-wider text-text-muted">
                What the access token will carry
              </p>
              <pre className="max-h-72 overflow-y-auto rounded-lg border border-surface-2 bg-bg-primary p-3 font-mono text-[11px] leading-relaxed text-text-primary">
                <code data-testid="preview-payload-json">
                  {JSON.stringify(previewPayload, null, 2)}
                </code>
              </pre>
              {Object.keys(previewPayload).length === 0 && (
                <p className="mt-2 text-[10px] text-text-muted">
                  No custom claims will be emitted with these scopes. The token carries only the standard JWT claims.
                </p>
              )}
              <p className="mt-2 text-[10px] text-text-muted">
                The token also carries the standard JWT claims (iss, sub, aud, exp, iat, jti, scopes, email) - managed by the JWT service.
              </p>
            </div>
          )}
        </div>
      )}

      {/* Use my session - convenience button to seed the
          preview with the admin's own claims (so the namespaced
          RBAC role / permission claims have a concrete value). */}
      <div className="border-t border-surface-2 pt-3">
        <p className="flex items-center gap-1.5 text-[10px] text-text-muted">
          <User size={10} />
          Logged in as <span className="font-mono text-text-secondary">{user?.email ?? '—'}</span>.
          {' '}RBAC role names shown in the preview are placeholder values for the admin role.
        </p>
      </div>
    </div>
  )
}
