"""File-system-backed repository for admin actions targeting users.

On-disk layout (relative to ``settings.storage_path``):

* ``<storage>/admin_actions/<target_user_id>/<action_id>.json`` — one
  document per admin action. The two-level directory structure
  isolates the per-user fan-out, so ``list_for_user`` is a single
  ``<target_user_id>/*.json`` glob.

The pre-refactor ``AdminActionService`` had two backend-bypass bugs:

1. ``__init__`` constructed ``fsspec.filesystem("file")`` directly,
   ignoring ``Settings.storage_backend`` (``services/admin_action.py:76``).
2. ``record_action`` used ``os.makedirs(os.path.dirname(...))`` to
   create the per-user sub-directory (``services/admin_action.py:105``),
   bypassing the fsspec abstraction. On any non-``file`` backend the
   ``os.makedirs`` would attempt to create a path on the local
   filesystem that the cloud backend never sees, and the subsequent
   ``_afs.write_json`` would write the file to the wrong location
   (or raise a missing-bucket error on first write).

Both bugs are fixed in this repository: ``BaseFileRepository`` builds
the fsspec filesystem from ``Settings.storage_backend``, and
``_ensure_parent`` is the single place that handles directory
creation in a backend-agnostic way.
"""

from typing import Any, Dict, List, Optional, Tuple

from authglow.repositories.file.base import BaseFileRepository
from authglow.repositories.protocols import AdminActionRepository, Record


class FileAdminActionRepository(BaseFileRepository, AdminActionRepository):
    """File-backed implementation of :class:`AdminActionRepository`.

    Each action is stored as a flat dict (the pre-refactor
    ``AdminAction.to_dict()`` shape) so the repo can stay
    backend-agnostic without dragging the dataclass model into the
    Protocol. The protocol exposes ``Record = Dict[str, Any]`` for
    the same reason.
    """

    _subdir = "admin_actions"

    # ------------------------------------------------------------------
    # Path helpers
    # ------------------------------------------------------------------

    def _user_dir(self, target_user_id: str) -> str:
        """Return the on-disk directory for a target user's actions."""
        return self._path(target_user_id)

    def _action_path(self, target_user_id: str, action_id: str) -> str:
        """Return the on-disk path for a single action."""
        return self._path(f"{target_user_id}/{action_id}.json")

    # ------------------------------------------------------------------
    # Protocol: record
    # ------------------------------------------------------------------

    async def record(
        self,
        *,
        admin_user_id: str,
        admin_email: str,
        action_type: str,
        target_user_id: str,
        target_user_email: Optional[str] = None,
        details: Optional[Dict[str, Any]] = None,
        ip_address: Optional[str] = None,
    ) -> None:
        """Append a new admin-action record.

        The ``id`` (UUID) and ``timestamp`` (UTC ISO-8601) are
        generated by the repository so the service layer does not
        have to expose its internal ``AdminAction`` dataclass to the
        Protocol. Returns ``None`` — callers that need the persisted
        record can call ``list_for_user`` and filter client-side
        (no current caller needs the round-trip).
        """
        from uuid import uuid4

        from authglow.core.datetime import utcnow

        record: Record = {
            "id": str(uuid4()),
            "admin_user_id": admin_user_id,
            "admin_email": admin_email,
            "action_type": action_type,
            "target_user_id": target_user_id,
            "target_user_email": target_user_email,
            "details": details or {},
            "ip_address": ip_address,
            "timestamp": utcnow().isoformat(),
        }
        path = self._action_path(target_user_id, record["id"])
        await self._write_json(path, record)

    # ------------------------------------------------------------------
    # Protocol: list_for_user
    # ------------------------------------------------------------------

    async def list_for_user(
        self,
        target_user_id: str,
        *,
        limit: int = 50,
        offset: int = 0,
    ) -> Tuple[List[Record], int]:
        """Return a paginated slice of actions against a user, plus
        the total count. Newest first (sorted by ``timestamp`` desc
        with a stable tie-break on ``id``)."""
        pattern = f"{self._user_dir(target_user_id)}/*.json"
        files = await self._glob(pattern)
        records: List[Record] = []
        for file_path in files:
            data = await self._read_json(file_path)
            if not isinstance(data, dict):
                continue
            records.append(data)
        records.sort(
            key=lambda r: (r.get("timestamp") or "", r.get("id") or ""),
            reverse=True,
        )
        total = len(records)
        return records[offset : offset + limit], total
