"""File-backed persistence for OAuth2 authorization codes.

Authorization codes are short-lived single-use secrets (10-minute
window by default). The file is named after the plaintext code
(no HMAC lookup is needed — the code is already a high-entropy
random secret). The repository owns:

* the file layout (``<storage>/auth_codes/{code}.json``);
* the JSON serialisation of the ``AuthorizationCode`` model;
* the ``get_by_code`` policy: absent / corrupt / expired (and
  auto-deleted) / already-used all return ``None``;
* the ``mark_used`` CAS-protected update with bounded retries.

The on-disk format is the ``AuthorizationCode.model_dump(mode="json")``
dict. After the first ``mark_used``, the file gains a ``_version``
key (managed transparently by ``read_json_versioned`` /
``write_json_versioned`` — the version is popped from the dict
on read and not part of the model).

The service layer in ``services/oauth2.py`` keeps:

* the in-process ``named_lock`` that serialises cross-coroutine
  ``mark_code_as_used`` calls;
* the cross-process CAS retry loop (defensive — the repo's
  ``mark_used`` already retries, so the service's loop is a
  safety net for the future);
* the ``AuthorizationCode`` model construction (``code`` default
  factory, ``expires_at`` calculation);
* the client / scope / redirect-uri / grant-type verification
  methods (those delegate to ``client_storage`` and ``settings``,
  not to this repository).
"""

from typing import Optional

from authglow.core.config import Settings
from authglow.core.datetime import utcnow
from authglow.models.token import AuthorizationCode
from authglow.repositories.file.base import BaseFileRepository
from authglow.repositories.protocols import AuthorizationCodeRepository


class FileAuthorizationCodeRepository(BaseFileRepository, AuthorizationCodeRepository):
    """Persists OAuth2 authorization codes as one JSON file per code.

    File layout::

        <storage_path>/auth_codes/{code}.json

    The ``code`` itself is the filename (it is already a 32-byte
    URL-safe random secret generated by the service — no HMAC
    lookup is needed).
    """

    _subdir = "auth_codes"
    MAX_CAS_RETRIES = 3

    def __init__(self, settings: Optional[Settings] = None) -> None:
        super().__init__(settings)

    @staticmethod
    def _filename(code: str) -> str:
        return f"{code}.json"

    def _path_for(self, code: str) -> str:
        return self._path(self._filename(code))

    # ------------------------------------------------------------------
    # CRUD
    # ------------------------------------------------------------------

    async def create(self, code: AuthorizationCode) -> None:
        """Persist a new authorization code. Overwrites any prior
        entry for the same code."""
        path = self._path_for(code.code)
        await self._write_json(path, code.model_dump(mode="json"))

    async def get_by_code(self, code: str) -> Optional[AuthorizationCode]:
        """Return the code, or ``None``.

        ``None`` is returned for:
          * missing file,
          * corrupt JSON,
          * invalid Pydantic payload,
          * already-used code,
          * expired code (file is auto-deleted).

        The ``_version`` field managed by ``read_json_versioned``
        is popped transparently — the model never sees it.
        """
        path = self._path_for(code)
        if not await self._exists(path):
            return None
        try:
            data, _ = await self._read_json_versioned(path)
        except (ValueError, TypeError):
            return None
        if data is None:
            return None
        try:
            auth_code = AuthorizationCode(**data)
        except Exception:
            return None
        if auth_code.used:
            return None
        if utcnow() > auth_code.expires_at:
            # Auto-delete expired codes on read (matches the
            # pre-refactor service behaviour).
            await self._delete(path)
            return None
        return auth_code

    async def mark_used(self, code: str) -> bool:
        """Atomically mark the code as used.

        Uses internal CAS via ``read_json_versioned`` /
        ``write_json_versioned`` to prevent double-redemption
        across processes. Returns ``True`` on the first successful
        use, ``False`` on subsequent uses / missing / corrupt /
        expired codes / after ``MAX_CAS_RETRIES`` unsuccessful
        CAS attempts.
        """
        path = self._path_for(code)
        for _ in range(self.MAX_CAS_RETRIES):
            if not await self._exists(path):
                return False
            try:
                data, version = await self._read_json_versioned(path)
            except (ValueError, TypeError):
                return False
            if data is None:
                return False
            try:
                auth_code = AuthorizationCode(**data)
            except Exception:
                return False
            if auth_code.used:
                return False
            if utcnow() > auth_code.expires_at:
                return False
            auth_code.used = True
            try:
                await self._write_json_versioned(path, auth_code.model_dump(mode="json"), version)
                return True
            except Exception:
                # ConcurrentWriteError from write_json_versioned
                # (or a transient I/O issue) — retry with a fresh
                # read on the next iteration.
                continue
        return False

    async def delete(self, code: str) -> None:
        """Remove the code. No-op if absent."""
        await self._delete(self._path_for(code))
