"""File-backed persistence for OAuth2 clients.

The repository owns the file layout, JSON serialisation, the
``_version`` field handling (transparent to callers), and the
versioned-write CAS used by the service's ``update_last_used``
and ``rotate_secret`` operations. The service layer in
``services/oauth_client.py`` owns the in-process ``named_lock``
that serialises cross-coroutine ``update_last_used`` /
``rotate_secret`` calls, the secret hashing, and the public
``create_client`` / ``get_client`` / ``update_client`` /
``delete_client`` / ``list_clients`` / ``verify_client_secret`` /
``verify_redirect_uri`` / ``update_last_used`` / ``rotate_secret``
/ ``generate_client_secret`` / ``is_scope_allowed`` /
``is_grant_type_allowed`` API.

File layout::

    <storage_path>/oauth_clients/<client_id>.json

The filename is the client_id directly (it is already a UUIDv4
generated by the service — no HMAC lookup is needed).
"""

from typing import List, Optional

from authglow.core.config import Settings
from authglow.models.oauth_client import OAuth2Client
from authglow.repositories.file.base import BaseFileRepository
from authglow.repositories.protocols import OAuth2ClientRepository


class FileOAuth2ClientRepository(BaseFileRepository, OAuth2ClientRepository):
    """Persists OAuth2 clients as one JSON file per client_id."""

    _subdir = "oauth_clients"

    def __init__(self, settings: Optional[Settings] = None) -> None:
        super().__init__(settings)

    def _path_for(self, client_id: str) -> str:
        return self._path(f"{client_id}.json")

    # ------------------------------------------------------------------
    # CRUD
    # ------------------------------------------------------------------

    async def create(self, client: OAuth2Client) -> None:
        """Persist a new client. Overwrites any prior entry for the
        same client_id."""
        path = self._path_for(client.client_id)
        await self._write_json(path, client.model_dump(mode="json"))

    async def get_by_id(self, client_id: str) -> Optional[OAuth2Client]:
        """Return the client, or ``None``.

        Missing file, corrupt JSON, or invalid Pydantic payload
        all return ``None``.
        """
        path = self._path_for(client_id)
        if not await self._exists(path):
            return None
        try:
            data, _ = await self._read_json_versioned(path)
        except (ValueError, TypeError):
            return None
        if data is None:
            return None
        try:
            return OAuth2Client(**data)
        except Exception:
            return None

    async def update(self, client: OAuth2Client) -> None:
        """Persist changes via a versioned write.

        The ``_version`` field is read from disk, compared to the
        expected version, and incremented by 1 on success. Raises
        ``ConcurrentWriteError`` if the on-disk version was bumped
        by another process between the read and the write — the
        service layer catches and retries (``update_last_used``,
        ``rotate_secret``).

        A freshly-created client (file has no ``_version`` field)
        is read as version 0, and the versioned write with
        ``expected=0`` succeeds and writes ``_version: 1`` — this
        matches the pre-refactor first-CAS-passes behaviour of
        the service-level loop.
        """
        path = self._path_for(client.client_id)
        _, version = await self._read_json_versioned(path)
        await self._write_json_versioned(path, client.model_dump(mode="json"), version)

    async def delete(self, client_id: str) -> bool:
        """Delete the client. Returns ``True`` on success, ``False``
        if the file was missing."""
        return await self._delete(self._path_for(client_id))

    async def list(
        self,
        *,
        limit: int = 100,
        offset: int = 0,
        active_only: bool = False,
    ) -> List[OAuth2Client]:
        """Return a paginated slice of clients, sorted by client_id."""
        paths = await self._glob(f"{self._storage_path}/*.json")
        clients: List[OAuth2Client] = []
        for path in paths:
            data = await self._read_json(path)
            if data is None:
                continue
            try:
                client = OAuth2Client(**data)
            except Exception:
                continue
            if active_only and not client.is_active:
                continue
            clients.append(client)
        clients.sort(key=lambda c: c.client_id)
        return clients[offset : offset + limit]
