"""File-system-backed repository for security events per user.

On-disk layout (relative to ``settings.storage_path``):

* ``<storage>/security_events/<user_id>/<event_id>.json`` — one
  document per security event. The two-level directory structure
  isolates the per-user fan-out, so ``list_for_user`` is a single
  ``<user_id>/*.json`` glob.

The pre-refactor ``SecurityEventService`` had two backend-bypass bugs:

1. ``__init__`` constructed ``fsspec.filesystem("file")`` directly,
   ignoring ``Settings.storage_backend`` (``services/security_event.py:72``).
2. ``record_event`` used ``os.makedirs(os.path.dirname(...))`` to
   create the per-user sub-directory (``services/security_event.py:99``),
   bypassing the fsspec abstraction. On any non-``file`` backend the
   ``os.makedirs`` would attempt to create a path on the local
   filesystem that the cloud backend never sees, and the subsequent
   ``_afs.write_json`` would write the file to the wrong location
   (or raise a missing-bucket error on first write).

Both bugs are fixed in this repository: ``BaseFileRepository`` builds
the fsspec filesystem from ``Settings.storage_backend``, and
``_ensure_parent`` is the single place that handles directory
creation in a backend-agnostic way.

The repository stores records as flat dicts (the pre-refactor
``SecurityEvent.to_dict()`` shape); the Pydantic ``SecurityEvent``
model in ``authglow.models.admin`` is kept for future typed
implementations and route response models but is not used by the
File protocol (matches ``LoginHistoryRepository`` and
``AdminActionRepository``).
"""

from typing import Any, Dict, List, Optional, Tuple

from authglow.repositories.file.base import BaseFileRepository
from authglow.repositories.protocols import Record, SecurityEventRepository


class FileSecurityEventRepository(BaseFileRepository, SecurityEventRepository):
    """File-backed implementation of :class:`SecurityEventRepository`."""

    _subdir = "security_events"

    # ------------------------------------------------------------------
    # Path helpers
    # ------------------------------------------------------------------

    def _user_dir(self, user_id: str) -> str:
        """Return the on-disk directory for a user's events."""
        return self._path(user_id)

    def _event_path(self, user_id: str, event_id: str) -> str:
        """Return the on-disk path for a single event."""
        return self._path(f"{user_id}/{event_id}.json")

    # ------------------------------------------------------------------
    # Protocol: record
    # ------------------------------------------------------------------

    async def record(
        self,
        *,
        user_id: str,
        event_type: str,
        email: Optional[str] = None,
        description: Optional[str] = None,
        ip_address: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> None:
        """Append a new security event record.

        The ``id`` (UUID) and ``timestamp`` (UTC ISO-8601) are
        generated by the repository so the service layer does not
        have to expose its internal ``SecurityEvent`` dataclass to
        the Protocol. Returns ``None`` — callers that need the
        persisted record can call ``list_for_user`` and filter
        client-side (no current caller needs the round-trip).
        """
        from uuid import uuid4

        from authglow.core.datetime import utcnow

        record: Record = {
            "id": str(uuid4()),
            "user_id": user_id,
            "event_type": event_type,
            "email": email,
            "description": description,
            "ip_address": ip_address,
            "metadata": metadata or {},
            "timestamp": utcnow().isoformat(),
        }
        path = self._event_path(user_id, record["id"])
        await self._write_json(path, record)

    # ------------------------------------------------------------------
    # Protocol: list_for_user
    # ------------------------------------------------------------------

    async def list_for_user(
        self,
        user_id: str,
        *,
        limit: int = 50,
        offset: int = 0,
    ) -> Tuple[List[Record], int]:
        """Return a paginated slice of security events for a user,
        plus the total count. Newest first (sorted by ``timestamp``
        desc with a stable tie-break on ``id``)."""
        pattern = f"{self._user_dir(user_id)}/*.json"
        files = await self._glob(pattern)
        records: List[Record] = []
        for file_path in files:
            data = await self._read_json(file_path)
            if not isinstance(data, dict):
                continue
            records.append(data)
        records.sort(
            key=lambda r: (r.get("timestamp") or "", r.get("id") or ""),
            reverse=True,
        )
        total = len(records)
        return records[offset : offset + limit], total
